baseURL: https://temporalinterferance.com 
languageCode: en-us
title: TI-Solutions
disableKinds:
  - taxonomy
params:
  description: |
    TI-Solutions develops cutting-edge Temporal Interference (TI) brain stimulation technology and devices for neuroscience research and future medical treatments.
  headercommentblock: |
    <!-- ######################################
         Content:         TI-Solutions
         Graphic Design:  Kevin Eason, z43.swiss
         Implementation:  Tobi Oetiker, oetiker.ch
         ###################################### -->
ignoreLogs:
  - warning-goldmark-raw-html
markup:
  goldmark:
    extensions:
      extras:
        delete:
          enable: true
        subscript:
          enable: true
        superscript:
          enable: true
      strikethrough: false